### ISSUE TITLE
Polygons on the map

### ISSUE THREAD

**Issue by Leleweb28** [nreese/enhanced_tilemap#13]
Hi nreese,
it's possible view the polygons (geo_shape) on the map and click on the polygon to make a space research that updates all the components of the dashboard?

Thanks

**Comment by nreese** [comment]
That feature is not currently implemented

**Comment by Leleweb28** [comment]
How can I contact you in private for more detail?

Thanks,
Emanuele

**Comment by nreese** [comment]
Whats your email address?

**Comment by Leleweb28** [comment]
leleweb28atliberodotit

**Comment by nreese** [comment]
Is that an email address? What is the domain?

**Comment by Leleweb28** [comment]
Yes, that's my e-mail address... Leleweb28@libero.it. I avoid it clear writing to avoid spam

**Comment by skorski** [comment]
I'd be interested in this feature as well.  If you need some help please let me know.

**Comment by nreese** [comment]
The latest release allows for rendering geo_shape fields from saved search results on the map. Have you tried that?

**Comment by Leleweb28** [comment]
I have try that, but I need to visualize the polygons on map. Polygons are in index of Elastic-Search (geo_shape field). Click on polygon start geospatial search on Elastic Search. Search like when using the polygon filter tool and draw a polygon. Index that contains the polygons is selected in option configuration.

I think that is better adding a new "Map Overlays" configuration, like point of interest layer, with list of saved search filter on geo_shape index with only type polygon.

The use case is:
I have one index with points and one index with polygons. On map I want to visualize points and polygons. Click on single polygon start search (example {"geo_polygon":{"location":{"points":[[16.8441,41.03327],[16.87843,41.1104],[16.77612,41.13161]]}}}) and on map visualized only points result of search.

**Comment by nreese** [comment]
I have pushed a commit to master that will allow for clicking on a polygon and generating a filter. 

To install from master, clone the git repo under kibana/plugins.  Change the version number in package.json to your kibana version. Restart kibana.

**Comment by Leleweb28** [comment]
I have installed master version but not see the polygons on map for error Invalid GeoJSON object. I have saved the query with polygon and selected on Map Overlays option (POI Layer). The query get all (*) on index with name "geo_shape".

INDEX geo_shape:
{ "_index": "geo_shape",
  "_type": "default",
  "_id": "3",
  "_score": 1,
  "_source": {
    "strada": "strada_1",
    "location_point": [17.05627, 41.24651 ],
    "location_polygon": { "type": "polygon",
      "coordinates": [[[15.94666,41.05864],[16.75415,40.3884],[17.49023,41.31495],[15.94666,41.05864]]]
    }
  }
}

The error on browser console is:
Error: Invalid GeoJSON object.
    at Function.geometryToLayer (:5601/bundles/kibana.bundle.js?v=14438:49)
    at e.addData (:5601/bundles/kibana.bundle.js?v=14438:49)
    at e.addData (:5601/bundles/kibana.bundle.js?v=14438:49)
    at e.initialize (:5601/bundles/kibana.bundle.js?v=14438:49)
    at new e (:5601/bundles/kibana.bundle.js?v=14438:47)
    at Object.o.geoJson (:5601/bundles/kibana.bundle.js?v=14438:50)
    at POIs._createLayer (:5601/bundles/kibana.bundle.js?v=14438:137)
    at :5601/bundles/kibana.bundle.js?v=14438:137
    at processQueue (:5601/bundles/commons.bundle.js?v=14438:38)
    at :5601/bundles/commons.bundle.js?v=14438:38

**Comment by nreese** [comment]
Your data is not value geojson. The [geojson spec](http://geojson.org/geojson-spec.html) defines the `type` fields starting with a capital letter. Leaflet throws an error on the type string `polygon`. Elasticsearch is more lenient and allows the type to be all lower case.

Do a pull from master and the plugin should now support Elasticsearch's rules for geojson types.

**Comment by Leleweb28** [comment]
The new feature is fantastic. I'm testing polygon with thousand point.
I update you.

Thanks a lot

**Comment by Leleweb28** [comment]
I have a index with one polygon of 92000 point. If I click on the polygon the search not work. The error is: "Kibana is unable to store history items in your session because it is full and there don't seem to be items any items safe to delete.
This can usually be fixed by moving to a fresh tab, but could be caused by a larger issue. If you are seeing this message regularly, please file an issue at https://github.com/elastic/kibana/issues."

I think that better to use "quering with indexed shapes" like this: 
{  "geo_shape": {
    "location_shape": {
      "relation": "within",
      "indexed_shape": {
        "index": "xyl_zone",
        "type": "default",
        "id": "ZONA_20150303",
        "path": "location_area"
      }  }  }  }

Thanks a lot

**Comment by nreese** [comment]
I am going to close out this issue. The map now supports polygons from saved searches. These polygons can be clicked on to create filters.
