### ISSUE TITLE
Error heatmap in the dashboard

### ISSUE THREAD

**Issue by Leleweb28** [nreese/enhanced_tilemap#14]
Hi,
i have create a map, with the type heatmap in the dashboard failed:

Uncaught IndexSizeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0. (10.0.0../bundles/kibana.bundle.js?v=14438:51)
Version: 5.0.0
Build: 14438
Error: Uncaught IndexSizeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0. (10.0.0../bundles/kibana.bundle.js?v=14438:51)
    at window.onerror (10.0.0../bundles/commons.bundle.js?v=14438:69:13503)

Thanks

**Comment by nreese** [comment]
Are you still seeing this problem? What are the step taken to reproduce the error? Do you have a sample data set? I have been unable to produce such an error.

**Comment by nreese** [comment]
I have not heard any response so I am closing. Please reopen if the issue still exists.

**Comment by JacobBrandt** [comment]
Just saw someone has reported the same error on the original tile map.  I'll leave it here for reference so we can see if someone can figure out how to reproduce consistently.  https://github.com/elastic/kibana/issues/9478
