### ISSUE TITLE
Tilemap occasionally does not render lower half of map/dots

### ISSUE THREAD

**Issue by climbingsavage** [nreese/enhanced_tilemap#2]
On the dev-kibana instance, the tile map fails to render the lower half of both the background maps, and the primary visualization layer dots that are on the map. I can't figure out the conditions that cause this to happen though. Will update if I can figure out how to consistently re-create

**Comment by nreese** [comment]
I found a way to reproduce the problem. Open the time selection section. Then create a new enhanced tilemap visualization. Close the time selection section. The map does not resize to fit the full area.
