### ISSUE TITLE
Upgrade to 5.1.1

### ISSUE THREAD

**Issue by ytzlax** [nreese/enhanced_tilemap#20]
Please upgrade to 5.1.2

thanks

**Comment by nreese** [comment]
Kibana 5.1.2 has not been released yet. Do you mean 5.1.1?

**Comment by ytzlax** [comment]
yes

**Comment by nreese** [comment]
I have provided a [5.1.1](https://github.com/nreese/enhanced_tilemap/releases/tag/v5.1.1-2016-12-14) release.

**Comment by ytzlax** [comment]
thanks
