### ISSUE TITLE
Support for Kibana 5.1.2

### ISSUE THREAD

**Issue by jryd** [nreese/enhanced_tilemap#28]
Kibana 5.1.2 was recently released:

https://www.elastic.co/blog/kibana-5-1-2-and-4-6-4-released

Are you able to add support for the latest version?

**Comment by nreese** [comment]
I have just published a 5.1.2 release. Give it a spin and let me know if there are any problems

**Comment by nreese** [comment]
Did the release give you any problems? I am going to close the ticket unless I here otherwise

**Comment by jryd** [comment]
No I didn't experience any issues. Worked perfectly.
