### ISSUE TITLE
Legend shows looonng floats

### ISSUE THREAD

**Issue by climbingsavage** [nreese/enhanced_tilemap#3]
Values in the legend can display floats, i.e. 96.000000000000000001, which is unnecessary level of fidelity. Values should be rounded to int or at most decimal with 1 or two digits beyond decimal place i.e. 96 or 96.01

**Comment by nreese** [comment]
fixed with commit https://github.com/nreese/enhanced_tilemap/commit/0731ae20054af38efe0da9434ac7e66306016c1c
