### ISSUE TITLE
Circular reference to "MapFactory" found while resolving private deps: MapFactory -> ScaledCircleMarkerFactory

### ISSUE THREAD

**Issue by Valered** [nreese/enhanced_tilemap#31]
Hi all,
just trying this plugin but I face this problem:

Circular reference to "MapFactory" found while resolving private deps: MapFactory -> ScaledCircleMarkerFactory

How can I solve this? 
(using Kibana 5.1.2)

**Comment by nreese** [comment]
What are the steps taken to produce this error? I am building against 5.1 source and everything works fine. Can you please provide some more details.

**Comment by Valered** [comment]
Hi nreese, sorry it was my fault. 
I'm going to close the issue. 
By the way I've a question, is it possibile to filter POIs by time?

**Comment by nreese** [comment]
The answer is yes. Checkout the newest released version [2017-01-27](https://github.com/nreese/enhanced_tilemap/releases/tag/2017-01-27). This added the ability to apply kibana filters and time range to POI layers.

**Comment by varundbest** [comment]
@Valered, can you share what you did wrong?
