### ISSUE TITLE
Support for Kibana 5.2.0/5.2.1

### ISSUE THREAD

**Issue by quentinlesceller** [nreese/enhanced_tilemap#32]
[Kibana 5.2.0](https://www.elastic.co/blog/kibana-5-2-0-released) has been releases on January 31 (and also [Kibana 5.2.1]( https://www.elastic.co/blog/kibana-5-2-1-released) has been released yesterday)

Do you plan to update your plugin for these versions ?

**Comment by nreese** [comment]
There will eventually be a release. In the mean time, you can just clone the repo in the kibana plugins folder and change the version number to match your kibana version number

**Comment by mrguzzi** [comment]
I tried to do this since i want to resolve the filters label bug (id are shown instead of titles).
But without success. What am i doing wrong?

**Comment by nreese** [comment]
What steps did you take? What error messages are you receiving?

**Comment by mrguzzi** [comment]
Hello

at the moment kibana is not seeing the enhanced tile map anymore since 
made some tries.
But in the beginning deleted the old folder in plugins and put the the 
expanded zip from the clone.
Than replaced the original package.json

{

	"name": "enhanced_tilemap",

	"version": "6.0.0-alpha1",

	"scripts": {

	"test": "gulp test"

	},

	"devDependencies": {

	"babel-core": "6.22.1",

	"babel-preset-es2015": "6.22.0",

	"babel-register": "6.22.0",

	"chai": "3.5.0",

	"gulp": "3.9.1",

	"gulp-mocha": "3.0.1",

	"jsdom": "9.9.1",

	"jsdom-global": "2.1.1"

	}

	}



with this one
{
     "name": "enhanced_tilemap",
     "version": "5.2.2"
}

because it gave me all errors on the dependencies. Do i needed them?
Tried also to follow the instructions under "development" but received 
error on Leafles.Mouseposition


What can i do now?

Thanks
Kind reguards,

Domenico Rella

Il 13/03/2017 15:50, Nathan Reese ha scritto:
> What steps did you take? What error messages are you receiving?
>

**Comment by mrguzzi** [comment]
I noticed that version were different between kibana and enhanced 
plugins so, after correcting, i see the following errors

Mar 13 16:06:25 localhost kibana: 
{"type":"log","@timestamp":"2017-03-13T15:06:25Z","tags":["info","optimize"],"pid":2745,"message":"Optimizing 
and caching bundles for kibana, timelion and status_page. This may take 
a few minutes"}







Mar 13 16:08:40 localhost kibana: 
{"type":"log","@timestamp":"2017-03-13T15:08:40Z","tags":["fatal"],"pid":2745,"level":"fatal","message":"Optimizations 
failure.\n\n    ERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\n 
Module not found: Error: Cannot resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/formatcoords/index 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n     @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
7:64-135\n    \n    ERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\n 
Module not found: Error: Cannot resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/mgrs/dist/mgrs.js 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n     @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
13:61-131\n    \n    ERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\n 
Module not found: Error: Cannot resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition.css 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n     @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
24:4-110\n    \n    ERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\n 
Module not found: Error: Cannot resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n     @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
25:4-106\n","error":{"message":"Optimizations failure.\n\n 
\u001b[1m\u001b[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\n 
Module not found: Error: Cannot resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/formatcoords/index 
in /usr/share/kibana/plugins/enhanced_t
Mar 13 16:08:40 localhost kibana: ilemap/public/vislib\n     @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
7:64-135\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\n 
Module not found: Error: Cannot resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/mgrs/dist/mgrs.js 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n     @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
13:61-131\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\n 
Module not found: Error: Cannot resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition.css 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n     @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
24:4-110\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\n 
Module not found: Error: Cannot resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n     @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
25:4-106\u001b[39m\u001b[22m\n","name":"Error","stack":"Error: 
Optimizations failure.\n\n    \u001b[1m\u001b[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\n 
Module not found: Error: Cannot resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/formatcoords/index 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n     @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
7:64-135\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\n 
Module not found: Err
Mar 13 16:08:40 localhost kibana: or: Cannot resolve 'file' or 
'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/mgrs/dist/mgrs.js 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n     @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
13:61-131\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\n 
Module not found: Error: Cannot resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition.css 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n     @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
24:4-110\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\n 
Module not found: Error: Cannot resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n     @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
25:4-106\u001b[39m\u001b[22m\n\n    at Object.exports.create 
(/usr/share/kibana/node_modules/boom/lib/index.js:21:17)\n    at 
FsOptimizer.failedStatsToError 
(/usr/share/kibana/src/optimize/base_optimizer.js:228:32)\n    at 
/usr/share/kibana/src/optimize/fs_optimizer.js:53:29\n    at 
Compiler.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compiler.js:181:13)\n at 
/usr/share/kibana/node_modules/webpack/lib/Compiler.js:403:12\n at 
Compiler.next 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)\n at 
Compiler.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:40:4)\n at 
Compiler.applyPluginsAsync 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)\n at 
Compiler.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compiler.js:400:9)\n at 
Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Co
Mar 13 16:08:40 localhost kibana: mpilation.js:577:13)\n    at 
Compilation.applyPluginsAsync 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:60:69)\n at 
Compilation.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compilation.js:572:10)\n at 
Compilation.next 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)\n at 
Compilation.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:4)\n 
at Compilation.applyPluginsAsync 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)\n at 
Compilation.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compilation.js:567:9)"}}
Mar 13 16:08:40 localhost kibana: FATAL { Error: Optimizations failure.
Mar 13 16:08:40 localhost kibana: #033[1m#033[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js
Mar 13 16:08:40 localhost kibana: Module not found: Error: Cannot 
resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/formatcoords/index 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib
Mar 13 16:08:40 localhost kibana: @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
7:64-135#033[39m#033[22m
Mar 13 16:08:40 localhost kibana: #033[1m#033[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js
Mar 13 16:08:40 localhost kibana: Module not found: Error: Cannot 
resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/mgrs/dist/mgrs.js 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib
Mar 13 16:08:40 localhost kibana: @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
13:61-131#033[39m#033[22m
Mar 13 16:08:40 localhost kibana: #033[1m#033[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js
Mar 13 16:08:40 localhost kibana: Module not found: Error: Cannot 
resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition.css 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib
Mar 13 16:08:40 localhost kibana: @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
24:4-110#033[39m#033[22m
Mar 13 16:08:40 localhost kibana: #033[1m#033[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js
Mar 13 16:08:40 localhost kibana: Module not found: Error: Cannot 
resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib
Mar 13 16:08:40 localhost kibana: @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
25:4-106#033[39m#033[22m
Mar 13 16:08:40 localhost kibana: at Object.exports.create 
(/usr/share/kibana/node_modules/boom/lib/index.js:21:17)
Mar 13 16:08:40 localhost kibana: at FsOptimizer.failedStatsToError 
(/usr/share/kibana/src/optimize/base_optimizer.js:228:32)
Mar 13 16:08:40 localhost kibana: at 
/usr/share/kibana/src/optimize/fs_optimizer.js:53:29
Mar 13 16:08:40 localhost kibana: at Compiler.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compiler.js:181:13)
Mar 13 16:08:40 localhost kibana: at 
/usr/share/kibana/node_modules/webpack/lib/Compiler.js:403:12
Mar 13 16:08:40 localhost kibana: at Compiler.next 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)
Mar 13 16:08:40 localhost kibana: at Compiler.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:40:4)
Mar 13 16:08:40 localhost kibana: at Compiler.applyPluginsAsync 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)
Mar 13 16:08:40 localhost kibana: at Compiler.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compiler.js:400:9)
Mar 13 16:08:40 localhost kibana: at Compilation.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compilation.js:577:13)
Mar 13 16:08:40 localhost kibana: at Compilation.applyPluginsAsync 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:60:69)
Mar 13 16:08:40 localhost kibana: at Compilation.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compilation.js:572:10)
Mar 13 16:08:40 localhost kibana: at Compilation.next 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)
Mar 13 16:08:40 localhost kibana: at Compilation.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:4)
Mar 13 16:08:40 localhost kibana: at Compilation.applyPluginsAsync 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)
Mar 13 16:08:40 localhost kibana: at Compilation.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compilation.js:567:9)
Mar 13 16:08:40 localhost kibana: cause:
Mar 13 16:08:40 localhost kibana: { Error: Optimizations failure.
Mar 13 16:08:40 localhost kibana: #033[1m#033[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js
Mar 13 16:08:40 localhost kibana: Module not found: Error: Cannot 
resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/formatcoords/index 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib
Mar 13 16:08:40 localhost kibana: @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
7:64-135#033[39m#033[22m
Mar 13 16:08:40 localhost kibana: #033[1m#033[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js
Mar 13 16:08:40 localhost kibana: Module not found: Error: Cannot 
resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/mgrs/dist/mgrs.js 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib
Mar 13 16:08:40 localhost kibana: @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
13:61-131#033[39m#033[22m
Mar 13 16:08:40 localhost kibana: #033[1m#033[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js
Mar 13 16:08:40 localhost kibana: Module not found: Error: Cannot 
resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition.css 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib
Mar 13 16:08:40 localhost kibana: @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
24:4-110#033[39m#033[22m
Mar 13 16:08:40 localhost kibana: #033[1m#033[31mERROR in 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js
Mar 13 16:08:40 localhost kibana: Module not found: Error: Cannot 
resolve 'file' or 'directory' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib
Mar 13 16:08:40 localhost kibana: @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
25:4-106#033[39m#033[22m
Mar 13 16:08:40 localhost kibana: at Object.exports.create 
(/usr/share/kibana/node_modules/boom/lib/index.js:21:17)
Mar 13 16:08:40 localhost kibana: at FsOptimizer.failedStatsToError 
(/usr/share/kibana/src/optimize/base_optimizer.js:228:32)
Mar 13 16:08:40 localhost kibana: at 
/usr/share/kibana/src/optimize/fs_optimizer.js:53:29
Mar 13 16:08:40 localhost kibana: at Compiler.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compiler.js:181:13)
Mar 13 16:08:40 localhost kibana: at 
/usr/share/kibana/node_modules/webpack/lib/Compiler.js:403:12
Mar 13 16:08:40 localhost kibana: at Compiler.next 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)
Mar 13 16:08:40 localhost kibana: at Compiler.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:40:4)
Mar 13 16:08:40 localhost kibana: at Compiler.applyPluginsAsync 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)
Mar 13 16:08:40 localhost kibana: at Compiler.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compiler.js:400:9)
Mar 13 16:08:40 localhost kibana: at Compilation.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compilation.js:577:13)
Mar 13 16:08:40 localhost kibana: at Compilation.applyPluginsAsync 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:60:69)
Mar 13 16:08:40 localhost kibana: at Compilation.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compilation.js:572:10)
Mar 13 16:08:40 localhost kibana: at Compilation.next 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)
Mar 13 16:08:40 localhost kibana: at Compilation.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:4)
Mar 13 16:08:40 localhost kibana: at Compilation.applyPluginsAsync 
(/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)
Mar 13 16:08:40 localhost kibana: at Compilation.<anonymous> 
(/usr/share/kibana/node_modules/webpack/lib/Compilation.js:567:9)
Mar 13 16:08:40 localhost kibana: data: { errors: [Object], warnings: 
[], publicPath: '/bundles/' },
Mar 13 16:08:40 localhost kibana: isBoom: true,
Mar 13 16:08:40 localhost kibana: isServer: true,
Mar 13 16:08:40 localhost kibana: output: { statusCode: 500, payload: 
[Object], headers: {} },
Mar 13 16:08:40 localhost kibana: reformat: [Function] },
Mar 13 16:08:40 localhost kibana: isOperational: true,
Mar 13 16:08:40 localhost kibana: data:
Mar 13 16:08:40 localhost kibana: { errors:
Mar 13 16:08:40 localhost kibana: [ 
'/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\nModule not 
found: Error: Cannot resolve \'file\' or \'directory\' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/formatcoords/index 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 7:64-135',
Mar 13 16:08:40 localhost kibana: 
'/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\nModule not 
found: Error: Cannot resolve \'file\' or \'directory\' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/mgrs/dist/mgrs.js 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 13:61-131',
Mar 13 16:08:40 localhost kibana: 
'/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\nModule not 
found: Error: Cannot resolve \'file\' or \'directory\' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition.css 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 24:4-110',
Mar 13 16:08:40 localhost kibana: 
'/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js\nModule not 
found: Error: Cannot resolve \'file\' or \'directory\' 
/usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition 
in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib\n @ 
/usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 
25:4-106' ],
Mar 13 16:08:40 localhost kibana: warnings: [],
Mar 13 16:08:40 localhost kibana: publicPath: '/bundles/' },
Mar 13 16:08:40 localhost kibana: isBoom: true,
Mar 13 16:08:40 localhost kibana: isServer: true,
Mar 13 16:08:40 localhost kibana: output:
Mar 13 16:08:40 localhost kibana: { statusCode: 500,
Mar 13 16:08:40 localhost kibana: payload:
Mar 13 16:08:40 localhost kibana: { statusCode: 500,
Mar 13 16:08:40 localhost kibana: error: 'Internal Server Error',
Mar 13 16:08:40 localhost kibana: message: 'An internal server error 
occurred' },
Mar 13 16:08:40 localhost kibana: headers: {} },
Mar 13 16:08:40 localhost kibana: reformat: [Function] }
Mar 13 16:08:40 localhost systemd: kibana.service: main process exited, 
code=exited, status=1/FAILURE
Mar 13 16:08:40 localhost systemd: Unit kibana.service entered failed state.
Mar 13 16:08:40 localhost systemd: kibana.service failed.
Mar 13 16:08:40 localhost systemd: kibana.service holdoff time over, 
scheduling restart.




Thanks
Kind reguards

Domenico Rella




Il 13/03/2017 16:04, Domenico Rella ha scritto:

**Comment by mrguzzi** [comment]
Hello, 
downloaded the zip, deleted old plugin, extracted the zip, creaned package.json from gulp and other dependences changing the plugin version according to 5.2.2 with i'm using.
I receive following errors:

Mar 13 16:08:40 localhost kibana: {"type":"log","@timestamp":"2017-03-13T15:08:40Z","tags":["fatal"],"pid":2745,"level":"fatal","message":"Optimizations failure.

    ERROR in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/formatcoords/index in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib
     @ /usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 7:64-135
    
    ERROR in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/mgrs/dist/mgrs.js in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib
     @ /usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 13:61-131
    
    ERROR in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition.css in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib
     @ /usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 24:4-110
    
    ERROR in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /usr/share/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition in /usr/share/kibana/plugins/enhanced_tilemap/public/vislib
     @ /usr/share/kibana/plugins/enhanced_tilemap/public/vislib/_map.js 25:4-106


thanks

**Comment by mrguzzi** [comment]
resolved running install as written under developer section.
It was necessary launch 
git config --global url."https://github.com/".insteadOf git@github.com:

because received error during install.
Thanks

**Comment by nreese** [comment]
Just published a [new release](https://github.com/nreese/enhanced_tilemap/releases/tag/v2017-03-17) that includes a download for kibana 5.2
