### ISSUE TITLE
POI Layer display only one result in coord 0, 0

### ISSUE THREAD

**Issue by TRISAF** [nreese/enhanced_tilemap#36]
Hi Nreese,

for sure i'm doing wrong and enhanced_tilemap works fine, but i have to ask to you
how to plot many markers in one poi layer.

I've loalded in an index 23 poi like this data:
 	Time 	                                geoip.location 	        Name
March 2nd 2017, 16:18:10.001	51.233333,6.783333	Dusseldorf
March 2nd 2017, 16:18:10.007	58.95,5.716667	        Stavanger

i've created a new search to query them and saved.
 
 then i've created a new enhanced_tilemap in kibana 5.2.0
using the same search to be sure that my data are good points:
i see points in map.
In option panel / Map Overlays i select the same search and ypur tool show me thegeoip.location field is available.

But clicking play i see only one marker in 0,0 coordinates with the label field with my data Name.

Can u help me ?

best regards 
Filippo

**Comment by TRISAF** [comment]
Hi Nreese,
did you have time to check this issue?

Do you need more details?
Thanks
Filippo

**Comment by nreese** [comment]
Sounds like the map is having a hard time parsing the geo points from the saved search response. Can you post a sample documents from the saved search response?

**Comment by TRISAF** [comment]
Something different,
i've re done the process to describe tu you how to reproduce it, and now works, but was more related to my points that have a geoip.location field and not the geo_point.

Sorry and my best compliments for this plugin.

Filippo

**Comment by TRISAF** [comment]
TKS
