### ISSUE TITLE
No tooltip formatter option

### ISSUE THREAD

**Issue by rgheleribefore** [nreese/enhanced_tilemap#39]
Hello
I can not find the tooltip formatter option as shown in the gif at home page. I already change both ES and Kibana to 5.0.2 and 5.1.2 and I can't found any clue. Do I need to include something to enable this feature?

Sorry to bother you.
![map aggregation options](https://cloud.githubusercontent.com/assets/24317998/23875308/5bca5f52-080f-11e7-9e8f-2aa46a644d68.png)

**Comment by nreese** [comment]
I have not published a release with that functionality yet. Follow the
instructions to deploy from source. I hope to get a published release out
some time in the next two weeks

**Comment by rgheleribefore** [comment]
Nice. Thank you very much to aswer so fast :)
