### ISSUE TITLE
popup shows global results

### ISSUE THREAD

**Issue by mrguzzi** [nreese/enhanced_tilemap#40]
Hello,
on kibana version 5.2.2 i noticed that the visualization in popup shows just for one second the result according to that scaled circle, after a while this popup is replaced with the same visualization with all the results without any filter on that geopoint.
Am i doing it wrong or it's a bug?

**Comment by nreese** [comment]
Can you provide more details? Are there any other user interactions? How about an animated gif showing the problem? I have not seen this before.

The popup will change when another marker is moused over. Is that happening?

**Comment by mrguzzi** [comment]
Hello, how can i register an animated gif?
I have an enhanced tile map with a bars chart as popup visualization
As i move the mouse on a circle at first i see this:

![image](https://cloud.githubusercontent.com/assets/25525911/23910101/f001e554-08d8-11e7-8cfd-eee87bb988df.png)

and after a while i see this

![image](https://cloud.githubusercontent.com/assets/25525911/23910166/14a31018-08d9-11e7-8257-d4391ff23de0.png)

wich shows all the result.
Actually the behavior is quite random as sometimes i see the partial result, somethimes all the result.
When i change marker is the same.
Thanks

**Comment by mrguzzi** [comment]
And here is the animated gif

![20170314-172358_capture](https://cloud.githubusercontent.com/assets/25525911/23910915/7b8ccd94-08db-11e7-81e4-4d82d2eb973f.gif)

**Comment by nreese** [comment]
Thanks for pointing this out. I am able to reproduce the issue now.

**Comment by nreese** [comment]
I have resolved the problem. Do a pull from master and test it out. If everything looks good, I will create a release today.

Thanks for finding this issue!
