### ISSUE TITLE
Cannot see the option to create pop-up visulization

### ISSUE THREAD

**Issue by Fengjun-Wang** [nreese/enhanced_tilemap#41]
Hi nreese,

I am using Kibana 5.1.2. 
I installed your enhanced_tilemap.
I created a enhanced tile map, it shows dots correctly, but I did not find where could I add popup for each dot. 
Could you have a look and give me some introductions?
![image](https://cloud.githubusercontent.com/assets/10376624/24050260/96e76e96-0b2e-11e7-81fd-d056e7433118.png)
![image](https://cloud.githubusercontent.com/assets/10376624/24050328/be245f46-0b2e-11e7-8fa3-fe756766cf4a.png)

**Comment by chintan-29** [comment]
I have the same issue. There is no option for that.

**Comment by nreese** [comment]
I just pushed a [new release](https://github.com/nreese/enhanced_tilemap/releases/tag/v2017-03-17) that contains the popup functionality. Install the new version and the option should be there.
