### ISSUE TITLE
Iframe Embed Issue

### ISSUE THREAD

**Issue by jyotiskab** [nreese/enhanced_tilemap#44]
After installing the plugin, I'm getting an iframe issue security error. This only occurs when the visualization is embedded in iframe. I opened up a static test.html with the iframe, and this is the error it shows:

Uncaught SecurityError: Blocked a frame with origin "http://localhost:5601" from accessing a cross-origin frame. (http://localhost:5601/bundles/kibana.bundle.js?v=14723:143)

![image](https://cloud.githubusercontent.com/assets/6498738/24633445/89ec2612-1896-11e7-8e80-bae4fbbab9a7.png)

**Comment by jyotiskab** [comment]
![iframe_issue](https://cloud.githubusercontent.com/assets/6498738/24585790/bc24c7b0-1760-11e7-9748-0709f3c8ce38.png)

**Comment by tony-cocco** [comment]
I just ran into this same issue. Do we have a fix or mitigation?

**Comment by nreese** [comment]
What browser are you running? How are you serving out the iframe html page? If you remove the enhanced tilemap visualization from the dashboard (and use only built in kibana visualizations), do your iframe issues persist?

**Comment by jyotiskab** [comment]
The issue happens on all three browsers (chrome, firefox, and IE). The issue is that

>  If you remove the enhanced tilemap visualization from the dashboard (and use only built in kibana visualizations), do your iframe issues persist?

Yes, any sort of iframe embedding throws this error, regardless of whether the visualization contains enhanced_tilemap. It's only after removing the plugin completely, the error goes away. 

It seems that the plugin uses both bower **and** npm to build.  Could this lead to an issue?
