### ISSUE TITLE
Cant File Release v2017-03-17 for 5.0.1

### ISSUE THREAD

**Issue by SubodhChettri** [nreese/enhanced_tilemap#46]
Cant find the plugin for v2017-03-17 for 5.0.1 
https://github.com/nreese/enhanced_tilemap/releases/download/v2017-03-17/enhanced-tilemap-v2017-03-17-5.0.2.zip

**Comment by nreese** [comment]
Just download and change the version number in the package.json file. It is too much work to make a separate release for each minor version of kibana
