### ISSUE TITLE
Version error on install

### ISSUE THREAD

**Issue by tonyrwoods** [nreese/enhanced_tilemap#49]
I have Kibana version 5.2.1 build 14707, however, I still get the below error when trying to install:

Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [enhanced_tilemap]. Expected [5.2.1]; found [5.0.2]"

**Comment by nreese** [comment]
just change the version number in package.json to 5.2.1. There are no source code differences between any of the 5.x downloads

**Comment by tonyrwoods** [comment]
Thanks for the quick response Nathan,

However, my package.json already has 5.2.1 defined:

[cid:image001.png@01D2A872.F9AFC5B0]

Thanks,

Anthony R. Woods
Sr. Services & Sales Architect, Enterprise Management Practice
Anthony.Woods@ca.com<mailto:Anthony.Woods@ca.com>
Mobile 901-233-4060

**Comment by nreese** [comment]
What version of kibana are you using?

**Comment by tonyrwoods** [comment]
Version 5.2.1

Thanks,

Anthony R. Woods
Sr. Services & Sales Architect, Enterprise Management Practice
Anthony.Woods@ca.com<mailto:Anthony.Woods@ca.com>
Mobile 901-233-4060

**Comment by nreese** [comment]
What is the version number in the file KIBANA_HOME/plugins/kibana/enhanced_tilemap/package.json? Is that set to 5.2.1?

**Comment by tonyrwoods** [comment]
Ok… now I’m embarrassed.  I was multitasking and neglected to expand the gz download.  I’m expanding now and I’m sure it’ll work.  Thanks for your help.

Thanks,

Anthony R. Woods
Sr. Services & Sales Architect, Enterprise Management Practice
Anthony.Woods@ca.com<mailto:Anthony.Woods@ca.com>
Mobile 901-233-4060

**Comment by tonyrwoods** [comment]
Correction: enhanced_tilemap is not showing in the plugins directory?  The install output says it was downloaded however:

wooan07mac1046:bin wooan07$ ./kibana-plugin install https://github.com/nreese/enhanced_tilemap/releases/download/v2017-03-17/enhanced-tilemap-v2017-03-17-5.0.2.zip
Attempting to transfer from https://github.com/nreese/enhanced_tilemap/releases/download/v2017-03-17/enhanced-tilemap-v2017-03-17-5.0.2.zip
Transferring 6440787 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [enhanced_tilemap]. Expected [5.2.1]; found [5.0.2]"


Thanks,

Anthony R. Woods
Sr. Services & Sales Architect, Enterprise Management Practice
Anthony.Woods@ca.com<mailto:Anthony.Woods@ca.com>
Mobile 901-233-4060

From: Tony Woods <Anthony.Woods@ca.com>
Date: Wednesday, March 29, 2017 at 12:46 PM
To: nreese/enhanced_tilemap <reply@reply.github.com>, nreese/enhanced_tilemap <enhanced_tilemap@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [nreese/enhanced_tilemap] Version error on install (#49)

Ok… now I’m embarrassed.  I was multitasking and neglected to expand the gz download.  I’m expanding now and I’m sure it’ll work.  Thanks for your help.

Thanks,

Anthony R. Woods
Sr. Services & Sales Architect, Enterprise Management Practice
Anthony.Woods@ca.com<mailto:Anthony.Woods@ca.com>
Mobile 901-233-4060
