### ISSUE TITLE
Uncaught ReferenceError: bars is not defined

### ISSUE THREAD

**Issue by Gualberto-Vannini** [nreese/enhanced_tilemap#50]
After the setup of the plugin, when i restarted Kibana 5.2.2 it was impossibile enter on it.
The only solution was delete the plugin. 
Any idea? 

![schermata 2017-04-14 alle 12 22 30](https://cloud.githubusercontent.com/assets/22340454/25040988/18d52ab2-210d-11e7-90a2-fa032dc29097.png)

**Comment by nreese** [comment]
I have not seen this before. What steps were taken to produce this error?

**Comment by Gualberto-Vannini** [comment]
I notice that this problem is with all the plugin in both my version 5.2.2 and 5.1.2 shared here 
https://www.elastic.co/guide/en/kibana/current/known-plugins.html

I just follow your suggestion {my path}/kibana-plugin install https://github.com/nreese/enhanced_tilemap/releases/download/v2017-03-17/enhanced-tilemap-v2017-03-17-5.2.2.zip

than i started elasticsearch and kibana and this error arrive. 

But maybe before than install any plugin I need to do something? or is enough write in the shell 
{my path}/kibana-plugin install https://github.com/nreese/enhanced_tilemap/releases/download/v2017-03-17/enhanced-tilemap-v2017-03-17-5.2.2.zip ?

**Comment by nreese** [comment]
Do you have any other plugins installed?

**Comment by nreese** [comment]
I am not able to reproduce the issue. I downloaded a clean kibana 5.2.2 verion. Installed the plugin with the command `./kibana-plugin install https://github.com/nreese/enhanced_tilemap/releases/download/v2017-03-17/enhanced-tilemap-v2017-03-17-5.2.2.zip`. And started kibana with the command `./kibana`. Everything started fine and I am able to create an enhanced tilemap visualization. I am runing OSX 10.10.3 with chrome 56.0.2924.87.

What is different about your setup? Do you have other plugins installed? Can you try with a clean version of kibana?

**Comment by nreese** [comment]
I am going to close since I can not reproduce the problem. Reopen if you still have the issue and repeatable steps to produce it
