### ISSUE TITLE
No kibana plugins found in archive

### ISSUE THREAD

**Issue by karnamonkster** [nreese/enhanced_tilemap#52]
Hi,
Currently running Kibana 5.3
Tried installing the latest release using the master.zip
getting an error:
```
[user@localhost kibana]# bin/kibana-plugin install file:///home/user/Downloads/enhanced_tilemap-master.zip 
Attempting to transfer from file:///home/user/Downloads/enhanced_tilemap-master.zip
Transferring 226372 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"
```
Whether this works with the latest Kibana?

**Comment by nreese** [comment]
The current releases do not support 5.3. Master supports 5.3. Try installing from Build plugins instructions

**Comment by nreese** [comment]
I just pushed a new release that supports 5.3. Reopen if you have any issues with the new release
