### ISSUE TITLE
Kibana 5.3 no map

### ISSUE THREAD

**Issue by laurent-richer** [nreese/enhanced_tilemap#53]
Hello,

I'v upgraded the following components 

-  ELK 5.2 to 5.3 

- enhanced_tilemap from 2017-01-27 to v2017-03-17

I can use the visualisation, but i cannot see any map, there is a blank screen instead and no errors in the logs.

Any help ?
Thx
Laurent

**Comment by nreese** [comment]
The current releases do not support 5.3. Master supports 5.3. Try installing from [Build plugins](https://github.com/nreese/enhanced_tilemap#build-plugin) instructions

**Comment by nreese** [comment]
I just pushed a new release that supports 5.3. Reopen issue if you have any issues
