### ISSUE TITLE
5.3 Release Download link does not work

### ISSUE THREAD

**Issue by karnamonkster** [nreese/enhanced_tilemap#55]
The new 5.3 release link does not work
[https://github.com/nreese/enhanced_tilemap/releases/download/v2017-04-19/enhanced-tilemap-v2017-04-19-5.3.0.zip]

**Comment by nreese** [comment]
Can you please provide some additional details. What is not working about it?

**Comment by karnamonkster** [comment]
Sorry about the issue, just a networking problem.
