### ISSUE TITLE
Support for Sub-aggregation

### ISSUE THREAD

**Issue by karnamonkster** [nreese/enhanced_tilemap#56]
Will it be possible to apply sub-aggregations to the map as currently the tile map shows nothing when used with other visualizations if we apply a filter query,  it removes the data points from the map

**Comment by nreese** [comment]
Can you provide an example. I am not sure what you mean

**Comment by karnamonkster** [comment]
Hi,
I started a thread on the issue I was facing, and thought enhanced tile map would help me fix this.
https://discuss.elastic.co/t/tile-map-disappears/82664/11
Let me know if this is possible

**Comment by karnamonkster** [comment]
Also our internal WMS compliant MAPs are not displayed, which used to work with normal "Tile Map" visualization
