### ISSUE TITLE
Error while trying to draw 2 different areas. 

### ISSUE THREAD

**Issue by alepuccetti** [nreese/enhanced_tilemap#69]
Setup:
I am using `kibana 5.6.0` and I cannot update to `5.6.1` because I am using search guard which is compatible with `5.6.0`. I checked the difference between `5.6.0` and `5.6.1` and the code difference is minimal and, for my understanding, it should not be related to my issue.

I do not know if it is a version incompatibility issue (I think this is unlikely) or a different issue.

I based my installation process on the answer on this issue https://github.com/nreese/enhanced_tilemap/issues/46

Error:
```
Fatal Error
TypeError: queryFilter.updateFilter is not a function. (In ‘queryFilter.updateFilter({model:{bool:{should:geoFilters}},source:existingFilter,type:type,alias:filterAlias(field,geoFilters.length)})‘, ‘queryFilter.updateFilter’ is undefined) (https://example.com/bundles/kibana.bundle.js?v=15523:300)
Version: 5.6.0
Build: 15523
Error: TypeError: queryFilter.updateFilter is not a function. (In ‘queryFilter.updateFilter({model:{bool:{should:geoFilters}},source:existingFilter,type:type,alias:filterAlias(field,geoFilters.length)})‘, ‘queryFilter.updateFilter’ is undefined) (https://exmaple.com/bundles/kibana.bundle.js?v=15523:300)
onerror@https://example.com/bundles/commons.bundle.js?v=15523:90:22037
Fatal Error
IndexSizeError (DOM Exception 1): The index is not in the allowed range. (https://example.com/bundles/kibana.bundle.js?v=15523:119)
Version: 5.6.0
Build: 15523
Error: IndexSizeError (DOM Exception 1): The index is not in the allowed range. (https://example.com/bundles/kibana.bundle.js?v=15523:119)
onerror@https://example.com/bundles/commons.bundle.js?v=15523:90:22037
Fatal Error
TypeError: null is not an object (evaluating ‘parent.clientWidth’) (https://example.com/bundles/kibana.bundle.js?v=15523:298)
Version: 5.6.0
Build: 15523
Error: TypeError: null is not an object (evaluating ‘parent.clientWidth’) (https://example.com/bundles/kibana.bundle.js?v=15523:298)
onerror@https://example.com/bundles/commons.bundle.js?v=15523:90:22037
```

**Comment by JacobBrandt** [comment]
It's a bug.  The updateFilter method mentioned in the error has been removed from the Kibana baseline.  We'll have to update filters with our own routine.

**Comment by alepuccetti** [comment]
I see, giving a second look to the kibana commits I see the change. I do not know much of JS, otherwise, I would try to fix it myself.

**Comment by alepuccetti** [comment]
@JacobBrandt any idea of if/when this will be fixed? This break one of the main plugin functionality in kibana.

**Comment by alepuccetti** [comment]
This seems to be a breaking change. Any idea when this will be fixed?

**Comment by alepuccetti** [comment]
Thank you 😉
